const answers = [
	{ v: 'm', t: "La resposta, amic meu, està volant al vent" },
	{ v: 'n', t: "Tan cert com que la pizza de pinya és deliciosa" },
	{ v: 'n', t: "No sé Rick, sembla falç" },
	{ v: 'n', t: "Quan l'infern sigui fred" },
	{ v: 'm', t: "A l'univers hi ha més estrelles que grans de sorra a la terra" },
	{ v: 'm', t: "Les roses són vermelles, les violetes són blaves. I aquesta pregunta és estúpida" },
	{ v: 's', t: "Ja de pas, pregunta si el cel és blau" },
	{ v: 'n', t: "Claro que si guapi" },
	{ v: 'n', t: "Nanai nanai" },
	{ v: 's', t: "Sí." },
	{ v: 's', t: "Tan cert com que e elevat a pi per i igual a menys u" },
	{ v: 's', t: "Evidentment!" },
	{ v: 's', t: "Al cap de 400 metres, trenqui a la dreta. Ahh perdó, m'he confós, la resposta és sí" },
	{ v: 'm', t: "Busca't la vida" },
	{ v: 'm', t: "Les estrelles estan borroses, no ho veig clar" },
	{ v: 'm', t: "No hi ha prou saviesa al món per respondre això" },
	{ v: 'm', t: "No ho sé. En veritat sí que ho sé, però no et vull respondre." },
	{ v: 'm', t: "No em pagues prou" },
	{ v: 'n', t: "No." },
	{ v: 'm', t: "Deixa'm en pau, que tinc feina" },
	{ v: 's', t: "Les estrelles diuen que probablement sí" },
	{ v: 'n', t: "Hi ha més possibilitats que em caigui un meteorit i trenqui la bola" },
	{ v: 'n', t: "Sí, i el meu to de veu és súper expressiu" },
	{ v: 'n', t: "L'Elon Musk també creia que els seus cotxes eren irrompibles i mira" },
	{ v: 's', t: "Clarament sí" },
	{ v: 's', t: "emmm... es clar" },
	{ v: 's', t: "Yep" },
];
