const artworks = [
	{ day: 1, prompt: "Draw 10.000 of something", title: "Tri * 10^4", info: "<p>The color hue of each triangle is the result of multiplying the col by the row.</p><p>It was a happy accident and visually awful, but I found interesting enough for keeping.</p>" },
	{ day: 3, prompt: "Space", title: "Cosmic rain", info: "<p>Circles moving downwards at a random speed each. Simple.</p>" },
	{ day: 4, prompt: "The next next Fidenza", title: "TranspDenza", info: "<p>Inspired in <em>The Next Fidenza</em>, but with high transparency lines.</p>" },
	{ day: 5, prompt: "Destroy a square", title: "Dequare", info: "<p>Points initially positioned making a square shape, and moved by a flow field generated by <em>perlin noise</em>.</p>" },
	{ day: 6, prompt: "Trade styles with a friend", title: "Ondulacions geogràfiques", info: "<p>Simple <em>flow fields</em>. The colors and the rest of parameters chosen by my brother.</p>" },
	{ day: 7, prompt: "Sol LeWitt Wall Drawing", title: "Metatron Joining", info: "<p>Inspired by <a href=\"https://www.artnet.com/galleries/krakow-witkin-gallery/one-wall-one-work-sol-lewitt-1\">One Wall, One Work | Sol LeWitt, Wall Drawing #815, March 1997</a>.</p><p>Sightly irregular concentric polygons where each vertex is joined to every vertex.</p>" },
	{ day: 8, prompt: "Single curve only", title: "Bezier", info: "<p>Bezier curve visual implementation.</p>" },
	{ day: 9, prompt: "Architecture", title: "Domes", info: "<p>Recursive mirrored trees</p>" },
	{ day: 10, prompt: "Machine learning, wrong answers only", title: "Machine copying human", info: "<p></p>" },
];