const artworks = [
	{  day:  1,     prompt: "Perfect loop / Infinite loop / endless GIFs",                                                      title: "SnowFlake",                  info: "Recursive snowflakes"  },
	{  day:  2,     prompt: "Made in 10 minutes",                                                                               title: "Symmetric Bubbles",          info: "Symmetry always work<br>Sorry, It took me almost 20 minutes..."  },
	{  day:  3,     prompt: "Glitch Art",                                                                                       title: "",   info: "I made it with paint. I used to do that when I was yopung         It was   "  },
	// {  day:  4,     prompt: "Intersections",                                                                                    title: "",   info: ""  },
	// {  day:  5,     prompt: "Debug view",                                                                                       title: "",   info: ""  },
	// {  day:  6,     prompt: "Steal Like An Artist",                                                                             title: "",   info: ""  },
	// {  day:  7,     prompt: "Sample a color palette from your favorite movie/album cover",                                      title: "",   info: ""  },
	// {  day:  8,     prompt: "Signed Distance Functions",                                                                        title: "",   info: ""  },
	// {  day:  9,     prompt: "Plants",                                                                                           title: "",   info: ""  },
	// {  day: 10,     prompt: "Generative music",                                                                                 title: "",   info: ""  },
	// {  day: 11,     prompt: "Suprematism",                                                                                      title: "",   info: ""  },
	// {  day: 12,     prompt: "Tessellation",                                                                                     title: "",   info: ""  },
	// {  day: 13,     prompt: "Something you've always wanted to learn",                                                          title: "",   info: ""  },
	// {  day: 14,     prompt: "Aesemic",                                                                                          title: "",   info: ""  },
	// {  day: 15,     prompt: "Sine waves",                                                                                       title: "",   info: ""  },
	// {  day: 16,     prompt: "Reflection of a reflection",                                                                       title: "",   info: ""  },
	// {  day: 17,     prompt: "A grid inside a grid inside a grid",                                                               title: "",   info: ""  },
	// {  day: 18,     prompt: "Definitely not a grid",                                                                            title: "",   info: ""  },
	// {  day: 19,     prompt: "Black and white",                                                                                  title: "",   info: ""  },
	// {  day: 20,     prompt: "Art Deco",                                                                                         title: "",   info: ""  },
	// {  day: 21,     prompt: "Persian Rug",                                                                                      title: "",   info: ""  },
	// {  day: 22,     prompt: "Shadows",                                                                                          title: "",   info: ""  },
	// {  day: 23,     prompt: "More Moiré",                                                                                       title: "",   info: ""  },
	// {  day: 24,     prompt: "Textile",                                                                                          title: "",   info: ""  },
	// {  day: 25,     prompt: "Yayoi Kusama",                                                                                     title: "",   info: ""  },
	// {  day: 26,     prompt: "My kid could have made that",                                                                      title: "",   info: ""  },
	// {  day: 27,     prompt: "In the style of Hilma Af Klint",                                                                   title: "",   info: ""  },
	// {  day: 28,     prompt: "Generative poetry",                                                                                title: "",   info: ""  },
	// {  day: 29,     prompt: "Maximalism",                                                                                       title: "",   info: ""  },
	// {  day: 30,     prompt: "Minimalism",                                                                                       title: "",   info: ""  },
	// {  day: 31,     prompt: "Deliberately break one of your previous images, take one of your previous works and ruin it.",     title: "",   info: ""  },
];
